# Generated by Django 3.0.3 on 2020-07-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0002_auto_20200715_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
