# Generated by Django 3.0.3 on 2020-07-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daraja', '0003_delete_greeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lipa_na_mpesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
