# Generated by Django 3.0.3 on 2020-07-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0005_lipa_na_mpesa_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lipa_na_mpesa',
            name='name',
        ),
    ]
