# Generated by Django 3.0.3 on 2020-07-17 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0006_remove_lipa_na_mpesa_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipa_na_mpesa',
            name='Amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lipa_na_mpesa',
            name='Balance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lipa_na_mpesa',
            name='CheckoutRequestID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lipa_na_mpesa',
            name='MerchantRequestID',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lipa_na_mpesa',
            name='MpesaReceiptNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lipa_na_mpesa',
            name='ResultCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lipa_na_mpesa',
            name='ResultDesc',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lipa_na_mpesa',
            name='TransationDate',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='lipa_na_mpesa',
            name='phonenumber',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
