# Generated by Django 3.0.3 on 2020-07-17 14:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0007_auto_20200717_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lipa_na_mpesa',
            name='TransationDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 14, 31, 1, 183361, tzinfo=utc)),
        ),
    ]
