# Generated by Django 3.0.3 on 2020-07-17 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0008_auto_20200717_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lipa_na_mpesa',
            options={'verbose_name': 'Lipa Na Mpesa Payment', 'verbose_name_plural': 'Lipa Na Mpesa Payments'},
        ),
        migrations.AlterField(
            model_name='lipa_na_mpesa',
            name='TransationDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
