# Generated by Django 3.0.3 on 2020-07-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0009_auto_20200717_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='C2BPaymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionType', models.CharField(max_length=13)),
                ('TransID', models.CharField(max_length=12)),
                ('TransTime', models.CharField(max_length=20)),
                ('TransAmount', models.FloatField()),
                ('BusinessShortCode', models.CharField(max_length=12)),
                ('BillRefNumber', models.CharField(max_length=20)),
                ('InvoiceNumber', models.CharField(max_length=20)),
                ('OrgAccountBalance', models.FloatField()),
                ('ThirdPartyTransID', models.CharField(max_length=20)),
                ('MSISDN', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=20)),
                ('MiddleName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Customer To Business Payments',
                'verbose_name_plural': 'Customer To Business Payment',
                'ordering': ['TransTime'],
            },
        ),
        migrations.AlterModelOptions(
            name='lipa_na_mpesa',
            options={'ordering': ['-TransationDate'], 'verbose_name': 'Lipa Na Mpesa Payment', 'verbose_name_plural': 'Lipa Na Mpesa Payments'},
        ),
    ]
