# Generated by Django 3.1.2 on 2020-11-11 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mike_admin', '0002_auto_20201109_2323'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daraja', '0010_auto_20200720_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckoutRequestID', models.CharField(max_length=50, null=True)),
                ('MerchantRequestID', models.CharField(max_length=30, null=True)),
                ('ResultCode', models.IntegerField(null=True)),
                ('ResultDescription', models.TextField(max_length=200, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mike_admin.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
