# Generated by Django 3.1.2 on 2020-11-20 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daraja', '0012_auto_20201112_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated', to=settings.AUTH_USER_MODEL),
        ),
    ]
