# Generated by Django 3.1.2 on 2020-12-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0013_auto_20201120_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2bpaymentmodel',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='initiate',
            name='CheckoutRequestID',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='initiate',
            name='MerchantRequestID',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
