# Generated by Django 3.1.2 on 2020-12-18 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mike_admin', '0006_auto_20201217_2014'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daraja', '0015_auto_20201218_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2bpaymentmodel',
            name='Service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mike_admin.service'),
        ),
        migrations.AddField(
            model_name='c2bpaymentmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
