# Generated by Django 3.1.2 on 2021-01-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mike_admin', '0009_auto_20210103_1951'),
        ('daraja', '0017_paypal'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypal',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paypal',
            name='paypal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paypal',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mike_admin.service'),
        ),
    ]
