# Generated by Django 3.1.2 on 2021-01-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0018_auto_20210115_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiate',
            name='mode',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
