# Generated by Django 3.0.3 on 2020-10-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201027_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='transaction_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
