# Generated by Django 3.0.3 on 2020-10-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
