# Generated by Django 3.1.2 on 2020-11-09 20:23

from django.db import migrations, models
import mike_admin.upload_handler


class Migration(migrations.Migration):

    dependencies = [
        ('mike_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services')),
                ('font_image', models.CharField(max_length=40)),
                ('home_page_text', models.TextField()),
                ('pricing', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='music',
            name='music',
            field=models.FileField(upload_to='Musics', validators=[mike_admin.upload_handler.validate_file_extension], verbose_name='Audio File'),
        ),
    ]
