# Generated by Django 3.0.3 on 2020-10-27 08:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mike_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d1cf5d70-d93f-4716-ad65-7f12567b1ce2'), primary_key=True, serialize=False),
        ),
    ]
