# Generated by Django 3.1.2 on 2020-11-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mike_admin', '0002_auto_20201109_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Facebook Link'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram Link'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publish Testimonial?'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Twitter Link'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publish Testimonial?'),
        ),
    ]
