# Generated by Django 3.0.3 on 2020-10-28 05:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mike_admin', '0002_auto_20201027_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.UUIDField(default=uuid.UUID('66f35034-08fb-4785-82d7-a09c9ddece1c'), primary_key=True, serialize=False),
        ),
    ]
