# Generated by Django 3.1.2 on 2020-11-22 16:17

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mike_admin', '0003_auto_20201122_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
