# Generated by Django 3.0.3 on 2020-10-28 07:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mike_admin', '0004_auto_20201028_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9cf05d3f-9eab-45ba-bbcb-6933e8b3fcf8'), primary_key=True, serialize=False),
        ),
    ]
