# Generated by Django 3.1.2 on 2020-12-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mike_admin', '0004_auto_20201122_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
