# Generated by Django 3.1.2 on 2020-12-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mike_admin', '0005_auto_20201216_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title']},
        ),
    ]
