# Generated by Django 3.0.3 on 2020-10-28 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mike_admin', '0005_auto_20201028_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1004f8e4-76d3-45ae-a79c-0d452d299979'), primary_key=True, serialize=False),
        ),
    ]
