# Generated by Django 3.1.2 on 2020-10-28 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mike_admin', '0006_auto_20201028_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9a5925a0-1b60-4e9e-91e0-190d7e392666'), primary_key=True, serialize=False),
        ),
    ]
