# Generated by Django 3.1.2 on 2021-01-03 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mike_admin', '0006_auto_20201217_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='name',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.account', verbose_name='Username Of the staff Member'),
            preserve_default=False,
        ),
    ]
