# Generated by Django 3.1.2 on 2021-01-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mike_admin', '0007_auto_20210103_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(max_length=35),
        ),
    ]
