# Generated by Django 3.1.2 on 2020-11-01 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mike_admin', '0007_auto_20201028_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6ac392aa-9da2-4ef2-b16f-7cac3bd512ec'), primary_key=True, serialize=False),
        ),
    ]
