# Generated by Django 3.1.2 on 2021-01-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mike_admin', '0008_auto_20210103_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
