# Generated by Django 3.1.2 on 2020-11-02 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mike_admin', '0008_auto_20201101_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e1e3fabb-6922-436a-9a57-8b35b5dfd872'), primary_key=True, serialize=False),
        ),
    ]
