# Generated by Django 3.1.2 on 2021-02-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mike_admin', '0010_categoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryitem',
            name='title',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
