# Generated by Django 3.1.2 on 2020-11-03 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mike_admin', '0010_auto_20201102_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='skiza_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='The generated Skiza Code'),
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.UUIDField(default=uuid.UUID('09690548-131d-44ca-b6a6-f98b43686261'), primary_key=True, serialize=False),
        ),
    ]
