# Generated by Django 3.1.2 on 2020-12-03 13:35

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20201203_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_editorjs_fields.fields.EditorJsTextField(),
        ),
    ]
