# Generated by Django 3.1.2 on 2021-01-03 16:32

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20201210_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Write Your Post Here'),
        ),
    ]
