# Generated by Django 3.1.2 on 2021-01-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20210103_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brief_information',
            field=models.TextField(blank=True, null=True, verbose_name='Write a brief post info here'),
        ),
    ]
