# Generated by Django 3.1.2 on 2021-01-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_post_brief_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Read Time'),
        ),
    ]
